[MVP release] Deploy a Java application with Open Liberty/WebSphere Liberty on an Azure Red Hat OpenShift 4 cluster
WASdev/azure.liberty.aro pull request #4
Opened 2021-08-17 08:09 UTC by majguo

## Description
This PR is to resolve the following issues:
* Fix issue #3 
* Fix issue #1
* Fix issue #2

## Change summary
* Support to create an ARO 4 cluster or reuse an existing one 
* Use deployment script to orchestrate the whole deployment process 
   * Install Open Liberty Operator from OperatorHub using CLI
   * Support to create or update the HTPasswd identity provider
   * Uploading user specified application package (.war) is optional
   * Support to choose Open Liberty/WebSphere Liberty base image
   * Support to choose Java 8/Java 11 runtime
   * Build application image or use an Open Liberty/WebSphere Liberty base image
   * Deploy Open Liberty Application to the cluster
* Update readme

## Marketplace offer for testing
To facilitate PR review, I updated the testing offer with the latest code changes included in the PR, so reviewers can try by themselves to test, verify and share their feedback:
* Open the [preview link](https://portal.azure.com/#create/microsoft_javaeeonazure_test.20191212-arm-rhel-was-nd-v9-cluster-previewazure-liberty-aro) in Azure portal
   * If you see **Could not create the marketplace item**, click your profile at the top-right of the page > Switch directory > Select "WAS-MSFT-TEAM"
* Click **Create** to start the offer 

## Test cases
The following two cases have already been verified before sending out the PR:
* Create a new ARO4 cluster, user uploaded app, Open Liberty base image, Java 8 runtime;
* Use an existing ARO4 cluster, user uploaded app, Open Liberty base image, Java 8 runtime;
* Use an existing ARO4 cluster, user uploaded app, WebSphere Liberty base image, Java 11 runtime;
* Use an existing ARO4 cluster, no user app, Open Liberty base image, Java 8 runtime;
* Use an existing ARO4 cluster, no user app app, WebSphere Liberty base image, Java 11 runtime;

Signed-off-by: Jianguo Ma <jiangma@microsoft.com>

2021-08-18 16:12 UTC, edburns commented on pom.xml
> +        <version>1.0.7</version>
Please use version 1.0.10, the latest.

2021-08-18 16:20 UTC, edburns commented on src/main/arm/deploy.azcli
> +#!/bin/bash
I prefer to keep `src/main/arm` for things that end up in the `-arm-assembly.zip` file. However, I see you have several useful `.azcli` files here.  The appear to be for invoking directly by a human at the command line.  Where should we put them?
- They are certainly not ARM templates.
- We keep `src/main/scripts` for scripts that are invoked by the ARM templates.
We have not defined a place for scripts that are intended to be invoked directly by a human.
How about `src/main/cli` ?

2021-08-18 16:23 UTC, edburns commented on src/main/arm/uploadApp.azcli
> +#!/bin/bash
See comment tag src/main/cli.

2021-08-18 16:24 UTC, edburns commented on src/main/scripts/build-image.sh
> +dockerFileTemplate=$5
Good practice not exporting unless necessary.

2021-08-18 16:27 UTC, edburns requested changes
See comment `src/main/cli`

2021-08-19 02:52 UTC, majguo commented on pom.xml
> +        <version>1.0.7</version>
Fixed in 5fea6af.

2021-08-19 02:55 UTC, majguo commented on src/main/arm/deploy.azcli
> +#!/bin/bash
Thanks Ed for your good suggestion, fixed in 5fea6af and another pull request to azure-javaee-iaas:
* https://github.com/Azure/azure-javaee-iaas/pull/20

So pls help review [azure-javaee-iaas-pr-20](https://github.com/Azure/azure-javaee-iaas/pull/20) and get it merged first before approving this PR.

2021-08-19 02:55 UTC, majguo commented on src/main/arm/uploadApp.azcli
> +#!/bin/bash
See my comments above.

2021-08-19 16:01 UTC, edburns approved these changes

2021-08-19 20:44 UTC, pbaity commented on src/main/arm/createUiDefinition.json
> +                                "toolTip": "Use only allowed characters.",
Can we add a description of what characters are allowed here so a user doesn't have to fail the validation to find out?

2021-08-19 20:44 UTC, pbaity commented on src/main/arm/createUiDefinition.json
> +                        "toolTip": "Select 'Yes' to deploy your application, or select 'No' to deploy a default 'hello world' open liberty application.",
Less important, but you may want to capitalize "hello world" and "open liberty" (they are capitalized elsewhere)

2021-08-19 21:51 UTC, NottyCode commented on src/main/arm/createUiDefinition.json
> +            "pullSecret": "[steps('Cluster').createClusterInfo.pullSecret]",
Make this a secure string.

2021-08-20 03:25 UTC, majguo commented on src/main/arm/createUiDefinition.json
> +                                "toolTip": "Use only allowed characters.",
Thanks. Fixed in af2be56.

2021-08-20 03:26 UTC, majguo commented on src/main/arm/createUiDefinition.json
> +                        "toolTip": "Select 'Yes' to deploy your application, or select 'No' to deploy a default 'hello world' open liberty application.",
Thanks. Fixed in af2be56.

2021-08-20 03:26 UTC, majguo commented on src/main/arm/createUiDefinition.json
> +            "pullSecret": "[steps('Cluster').createClusterInfo.pullSecret]",
Thanks. Fixed in af2be56.

2021-08-20 14:28 UTC, venu-nb commented on src/main/scripts/Dockerfile.template
> +RUN configure.sh
The dockerfile Dockerfile.template is similar to the Dockerfile_wlp.template except for one comment at line 15, # Open Liberty base image and # WebSphere Liberty base image.

2021-08-20 16:44 UTC, pbaity approved these changes

2021-08-20 16:45 UTC, merged

2021-08-20 22:24 UTC, majguo commented on src/main/scripts/Dockerfile.template
> +RUN configure.sh
Yes, good catch. The purpose to keep two different templates is for future maintenance, e.g., paths for adding additional libraries are different for Open Liberty and WebSphere Liberty. Take DB drivers as an example:
* Open Liberty
   ```
   COPY --chown=1001:0 postgresql-42.2.4.jar /opt/ol/wlp/usr/shared/resources/
   ```

* WebSphere Liberty
   ```
   COPY --chown=1001:0 postgresql-42.2.4.jar /opt/ibm/wlp/usr/shared/resources/
   ```

2021-08-21 23:07 UTC, git4rk commented on src/main/arm/createUiDefinition.json
> +                    "text": "Please select one user assigned managed identity granted with contributor role of the subscription.<br><br>You can find more details from the following articles:<li><a hr
Based on other [MSFT docs](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-manage-user-assigned-managed-identities?pivots=identity-mi-methods-azp&WT.mc_id=Portal-Microsoft_Azure_CreateUIDef#create-a-user-assigned-managed-identity), looks like `user-assigned` is preferred way, instead of "user assigned"

2021-08-21 23:07 UTC, git4rk commented on src/main/arm/createUiDefinition.json
> +                    "userAssignedIdentity": "Add user assigned managed identity granted with contributor role of the subscription to enable the application deployment."
user assigned -> user-assigned

2021-08-21 23:07 UTC, git4rk commented on README.md
> +1. If you check the resource group in [azure portal](https://portal.azure.com/), you will see a deploymentSript and/or a virtual network, an OpenShift cluster depending on if you choose to create a n
Typo: deploymentSript -> deploymentScript

2021-08-21 23:09 UTC, git4rk commented on src/main/arm/mainTemplate.json
> +                "description": "The ObjectID of the Resource Provider Service Principal"
Is it ObjectID or Object ID?

2021-08-22 18:48 UTC, git4rk commented on src/main/cli/deploy.azcli
> +	echo "Resource group with name" $resourceGroupName "could not be found. Creating new resource group.."
- Need spaces: `"Resource group with name<SPACE HERE>" $resourceGroupName "<SPACE HERE>could not be found`
- Please update all such occurrences

2021-08-22 18:48 UTC, git4rk commented on src/main/cli/deploy.azcli
> +	echo "Enter a resource group name"
Should be "name:"

2021-08-22 18:49 UTC, git4rk commented on src/main/cli/deploy.azcli
> +# Create storage account and upload appliation package file to storage account
typo: appliation -> application

2021-08-22 18:51 UTC, git4rk commented on src/main/cli/uploadApp.azcli
> +if [ ! -f "$appPackage" ] || [ -z "$subscriptionId" ]; then
Message below indicates "resourceGroupName" is empty. Should we be checking for that as well?

2021-08-22 18:55 UTC, git4rk commented on src/main/scripts/install.sh
> +    updatedReplicas=$(oc get deployment ${deploymentName} -n ${namespaceName} -o=jsonpath='{.status.updatedReplicas}')
Since we are calling `oc get deployment ${deploymentName}` each time, it will return different (latest) result. Should we call it only once and parse the json output to get replicas, readyReplicas, availableReplicas and updateReplicas from a single source?

2021-08-22 18:55 UTC, git4rk commented on src/main/scripts/install.sh
> +        updatedReplicas=$(oc get deployment ${deploymentName} -n ${namespaceName} -o=jsonpath='{.status.updatedReplicas}')
Same comment as https://github.com/WASdev/azure.liberty.aro/pull/4/files#r693542312

2021-08-22 18:56 UTC, git4rk commented on src/main/scripts/install.sh
> +    while [ $? -ne 0 ]
For debugging purpose, I think, we should log some data to $logFile within the loop as well.

2021-08-23 05:12 UTC, majguo commented on src/main/cli/deploy.azcli
> +	echo "Resource group with name" $resourceGroupName "could not be found. Creating new resource group.."
No additional spaces needed, based on my testing. Did you try and check the output?

2021-08-23 06:02 UTC, majguo commented on src/main/arm/createUiDefinition.json
> +                    "text": "Please select one user assigned managed identity granted with contributor role of the subscription.<br><br>You can find more details from the following articles:<li><a hr
Addressed in pull request #5.

2021-08-23 06:02 UTC, majguo commented on src/main/arm/createUiDefinition.json
> +                    "userAssignedIdentity": "Add user assigned managed identity granted with contributor role of the subscription to enable the application deployment."
Addressed in pull request #5.

2021-08-23 06:02 UTC, majguo commented on README.md
> +1. If you check the resource group in [azure portal](https://portal.azure.com/), you will see a deploymentSript and/or a virtual network, an OpenShift cluster depending on if you choose to create a n
Addressed in pull request #5.

2021-08-23 06:03 UTC, majguo commented on src/main/arm/mainTemplate.json
> +                "description": "The ObjectID of the Resource Provider Service Principal"
Addressed in pull request #5.

2021-08-23 06:03 UTC, majguo commented on src/main/cli/deploy.azcli
> +	echo "Enter a resource group name"
Addressed in pull request #5.

2021-08-23 06:03 UTC, majguo commented on src/main/cli/deploy.azcli
> +# Create storage account and upload appliation package file to storage account
Addressed in pull request #5.

2021-08-23 06:03 UTC, majguo commented on src/main/cli/uploadApp.azcli
> +if [ ! -f "$appPackage" ] || [ -z "$subscriptionId" ]; then
Addressed in pull request #5.

2021-08-23 06:03 UTC, majguo commented on src/main/scripts/install.sh
> +    updatedReplicas=$(oc get deployment ${deploymentName} -n ${namespaceName} -o=jsonpath='{.status.updatedReplicas}')
Addressed in pull request #5.

2021-08-23 06:03 UTC, majguo commented on src/main/scripts/install.sh
> +        updatedReplicas=$(oc get deployment ${deploymentName} -n ${namespaceName} -o=jsonpath='{.status.updatedReplicas}')
Addressed in pull request #5.

2021-08-23 06:03 UTC, majguo commented on src/main/scripts/install.sh
> +    while [ $? -ne 0 ]
Addressed in pull request #5.